from fastapi import APIRouter, BackgroundTasks, status
from models.meeting import ProcessMeetingRequest, ProcessMeetingResponse
from services.audio_processor import process_meeting
from services.supabase_client import insert_meeting

router = APIRouter()


@router.post(
    "/process-meeting",
    response_model=ProcessMeetingResponse,
    status_code=status.HTTP_202_ACCEPTED,
    summary="Process meeting audio",
    description=(
        "Accepts a Supabase audio URL, transcribes the audio, summarizes it, "
        "stores results in the meetings table, and sends an Expo push notification. "
        "Processing happens asynchronously — the endpoint returns 202 immediately."
    ),
)
async def process_meeting_endpoint(
    body: ProcessMeetingRequest,
    background_tasks: BackgroundTasks,
) -> ProcessMeetingResponse:
    # Insert row first using the meeting_id generated by the client
    await insert_meeting(
        meeting_id=body.meeting_id,
        audio_url=str(body.audio_url),
        push_token=body.push_token,
    )

    background_tasks.add_task(
        process_meeting,
        audio_url=str(body.audio_url),
        meeting_id=body.meeting_id,
        push_token=body.push_token,
    )
    return ProcessMeetingResponse(
        message="Meeting processing started.",
        meeting_id=body.meeting_id,
    )
